name: Deploy My Flutter Dock App

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.3"
          channel: "stable"

      - name: Cache Flutter dependencies
        uses: actions/cache@v3
        with:
          path: ${{ env.FLUTTER_HOME }}/.pub-cache
          key: ${{ runner.OS }}-flutter-install-cache-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.OS }}-flutter-install-cache-

      - name: Install dependencies
        run: flutter pub get

      - name: Build web
        run: flutter build web --base-href=/dock_app/

      - name: Verify index.html presence
        run: [[ -f build/web/index.html ]] && echo "index.html found" || echo "index.html NOT found, deployment might fail"

      - name: List build directory
        run: ls -R build/web

      - name: Add.nojekyll file
        run: touch build/web/.nojekyll

      - name: Deploy to GitHub Pages
       uses: peaceiris/actions-gh-pages@v3
       with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         publish_dir: build/web
         publish_branch: gh-pages